import Head from 'next/head'
import Layout from "./Layout";

function DefaultTemlpate({ children }) {
    return (
        <Layout>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <div className="grid grid-cols-2 grid-rows-1 gap-4">
                {children}
            </div>
        </Layout>
    )
}

export default DefaultTemlpate;
